// Catálogo — dados reais dos kits, verificados em disco.
const CATALOGO = [
 {id:"LSK 001", slug:"KIT-DEVWEB-AITMPL", nome:"Engenharia Web", tipo:"Galáxia espiral", classe:"O", constelacao:"Orion",
  skills:43, agents:20, cmds:25, hooks:6, mcps:5, kb:2392, mag:-1.6,
  desc:"O corpo mais massivo do catálogo. Arquitetura, backend, frontend, banco, API, testes, debug, git e deploy — a espinha de qualquer aplicação web.",
  destaque:"Traz a família <em>senior-*</em> completa e as skills de método — <em>brainstorming</em>, <em>clean-code</em>, <em>systematic-debugging</em> — que mudam mais o resultado que qualquer skill de framework."},
 {id:"LSK 002", slug:"KIT-SECURITY-SISTEM-AITMPL", nome:"Segurança de Sistemas", tipo:"Aglomerado globular", classe:"B", constelacao:"Draco",
  skills:29, agents:15, cmds:13, hooks:8, mcps:4, kb:1640, mag:1.2,
  desc:"Construir, auditar e defender app, CRM, site e API. Inclui 8 hooks que bloqueiam comandos destrutivos de verdade.",
  destaque:"Os hooks foram testados: <code>rm -rf /</code> bloqueado, <code>sh -c \"rm -rf /\"</code> também. Traz o <em>read-only-auditor</em>, que garante por construção não alterar nada."},
 {id:"LSK 003", slug:"KIT-DEVWEB-MOTION-AITMPL", nome:"Motion e Landing Pages", tipo:"Nebulosa de emissão", classe:"A", constelacao:"Lyra",
  skills:31, agents:4, cmds:4, hooks:0, mcps:4, kb:7792, mag:2.9,
  desc:"Sites e landing pages com animação. Design de alto padrão, scroll narrativo, 3D e imagem de produto animada.",
  destaque:"Contém <strong>web-motion</strong>, escrita do zero — 6 arquivos, 56 KB — porque o catálogo do aitmpl.com não tem nenhuma skill de animação web. Esta página foi construída com ela."},
 {id:"LSK 004", slug:"KIT-DEVOPS-CLOUD", nome:"DevOps e Cloud", tipo:"Aglomerado aberto", classe:"A", constelacao:"Centaurus",
  skills:1, agents:12, cmds:12, hooks:0, mcps:2, kb:488, mag:4.1,
  desc:"Kubernetes, Terraform, observabilidade e SRE. Só vale se você gerencia a própria infraestrutura.",
  destaque:"O README abre dizendo que você provavelmente não precisa dele. Se roda em Vercel ou Railway, o LSK 001 já cobre."},
 {id:"LSK 005", slug:"KIT-MARKETING", nome:"Marketing e Conteúdo", tipo:"Aglomerado aberto", classe:"K", constelacao:"Pavo",
  skills:13, agents:9, cmds:3, hooks:0, mcps:2, kb:576, mag:4.1,
  desc:"SEO, conteúdo, estratégia, concorrência e aquisição. O que traz gente para o site que os outros kits constroem.",
  destaque:"O <em>/conteudo</em> revisa o texto contra os vícios de IA — abertura genérica, tricolon em toda frase, \"não apenas X, mas Y\"."},
 {id:"LSK 006", slug:"KIT-CLAUDE-CODE", nome:"Claude Code", tipo:"Pulsar", classe:"O", constelacao:"Fornax",
  skills:8, agents:12, cmds:3, hooks:0, mcps:1, kb:804, mag:4.3,
  desc:"Criar skills, agents, slash commands, hooks e servidores MCP. É o kit que constrói os outros.",
  destaque:"Quando o catálogo não tem o que você precisa, <em>skill-creator</em> resolve. Foi assim que a skill de animação do LSK 003 nasceu."},
 {id:"LSK 007", slug:"KIT-MOBILE-AITMPL", nome:"Mobile iOS + Android", tipo:"Sistema binário", classe:"A", constelacao:"Gemini",
  skills:14, agents:5, cmds:3, hooks:0, mcps:4, kb:1452, mag:4.4,
  desc:"App para as duas lojas: React Native, Flutter ou nativo. Design mobile-first, backend, publicação e ASO.",
  destaque:"MCPs de simulador iOS e Android deixam a IA rodar o app e tirar screenshot, em vez de escrever código no escuro."},
 {id:"LSK 008", slug:"KIT-PRODUTO-PM", nome:"Produto e Gestão", tipo:"Aglomerado aberto", classe:"K", constelacao:"Libra",
  skills:3, agents:7, cmds:12, hooks:0, mcps:1, kb:328, mag:4.4,
  desc:"PRD, roadmap, backlog e priorização. Decidir o que construir, antes de qualquer kit técnico entrar.",
  destaque:"O <em>/definir-feature</em> separa explicitamente o validado da premissa. Se a lista de validado estiver vazia, ele diz — em vez de preencher."},
 {id:"LSK 009", slug:"KIT-DOCUMENTOS", nome:"Documentos e OCR", tipo:"Nebulosa de reflexão", classe:"G", constelacao:"Mensa",
  skills:11, agents:7, cmds:3, hooks:0, mcps:2, kb:6516, mag:4.5,
  desc:"Word, Excel, PDF, PowerPoint e digitalização com OCR. O kit menos técnico e o mais usado no dia a dia.",
  destaque:"O <em>/analisar-planilha</em> aponta célula mesclada, número como texto e data em formato misto <strong>antes</strong> de calcular. Esses quatro quebram agregação em silêncio."},
 {id:"LSK 010", slug:"KIT-IA-AGENTES", nome:"IA e Agentes", tipo:"Nebulosa planetária", classe:"B", constelacao:"Cygnus",
  skills:12, agents:7, cmds:2, hooks:0, mcps:2, kb:340, mag:4.5,
  desc:"Colocar IA dentro do produto: prompt, RAG, memória, agentes autônomos e avaliação de modelo.",
  destaque:"Traz <em>agent-tool-builder</em>: agente que alucina argumento quase sempre tem ferramenta mal desenhada, não prompt ruim."},
 {id:"LSK 011", slug:"KIT-DOCUMENTACAO", nome:"Documentação Técnica", tipo:"Aglomerado aberto", classe:"G", constelacao:"Norma",
  skills:4, agents:7, cmds:8, hooks:0, mcps:0, kb:384, mag:4.7,
  desc:"API, guias, changelog e diagramas. Inclui modelo C4 e Mermaid — diagrama que versiona em git como texto.",
  destaque:"O <em>/diagramar</em> lê o código antes de desenhar. Diagrama da arquitetura pretendida, em vez da real, é pior que nenhum."},
 {id:"LSK 012", slug:"KIT-PESQUISA", nome:"Pesquisa Profunda", tipo:"Aglomerado estelar", classe:"M", constelacao:"Telescopium",
  skills:2, agents:13, cmds:2, hooks:0, mcps:3, kb:264, mag:4.9,
  desc:"Um time completo com orquestrador: um coordena, outros pesquisam em frentes diferentes, um verifica, um sintetiza.",
  destaque:"O <em>fact-checker</em> é o que separa isto de uma busca no Google. Pesquisa sem verificação é acúmulo de link."},
 {id:"LSK 013", slug:"KIT-DADOS-IA", nome:"Dados e Machine Learning", tipo:"Nebulosa escura", classe:"B", constelacao:"Hydra",
  skills:4, agents:9, cmds:2, hooks:0, mcps:2, kb:292, mag:5.0,
  desc:"Pipeline, ETL, análise estatística, inferência causal e ML em produção.",
  destaque:"O <em>/analisar-dados</em> separa correlação de efeito desde o início — confundir os dois é o erro mais caro em análise de negócio."}
];
const CLASSES = {
  O:{cor:"#9BB0FF", nome:"Núcleo"},
  B:{cor:"#AEC5FF", nome:"Inteligência"},
  A:{cor:"#D6E2FF", nome:"Produto"},
  G:{cor:"#FFF3E3", nome:"Documento"},
  K:{cor:"#FFD2A1", nome:"Crescimento"},
  M:{cor:"#FFAE7B", nome:"Investigação"}
};
